version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db/size_chart_db

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: size_chart_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: